### ISSUE TITLE
Add console commands

### ISSUE THREAD

**Issue by MRuy** [SnoutBug/csgotts#2]
Add console commands:  

https://www.reddit.com/r/GlobalOffensive/comments/j96zhh/texttospeech_in_counterstrike_global_offensive/g8juquz/

* `!alias <target> <new-name>`
* `!mute <target>`
* `!voice <target> <female|male>`
* `!voicespeed <value>`
* `!readnames <0|1>` toggle if no value
* `!usealias <0|1>` toggle if no value
* `!usefiller <0|1>` toggle if no value
* `!combinemsg <0|1>` toggle if no value
* `!region <region>`

**Comment by SnoutBug** [comment]
Sadly, this is not doable in a way where it would still be efficient and user friendly, since the game does not print the messages the way you entered them. The second string will never be printed.
Commands like "!mute_PlayerOne" would work but "!mute PlayerOne" would not. That's why I decided against this feature, not to mention the issues we have by defining the player name.
What if the player was called "семечки"? 

Though, I have added a command that lets you skip messages by binding "!tts_skip" to a key in-game. (bind "o" "!tts_skip")
Thanks for your input!
